apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: sample-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      NodePort: 30006
  selector:
    name: result-app-pod
    app: sample-voting-app