apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: sample-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      NodePort: 30005
  selector:
    name: voting-app-pod
    app: sample-voting-app